version: '3.3'
services:
  orders:
    image: unmsm/curso-dycs-2018-2-orders:0.1-snapshot
    environment:
    - DATABASE_HOST=postgres
    volumes:
    - ./orders/src/main/resources/config.yaml:/opt/config.yaml
    ports:
      - 9000:9000
      - 9001:9001
    links:
    - postgres
  postgres:
    build: docker/postgres
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  prom-data:



